Name:           ghostty
Version:        1.3.1
Release:        1%{?dist}
Summary:        Fast, feature-rich, cross-platform terminal emulator

License:        MIT
URL:            https://ghostty.org
# PACKAGING.md is explicit that this has to be the release tarball, not
# GitHub's autogenerated source archive: the release tarball carries files
# preprocessed specifically to reduce the build-time dependency list (see the
# blueprint-compiler note below), and GitHub's own archive is missing them.
Source0:        https://release.files.ghostty.org/%{version}/%{name}-%{version}.tar.gz
Source1:        https://release.files.ghostty.org/%{version}/%{name}-%{version}.tar.gz.minisig
# Ghostty releases are minisign-signed, not GPG, so this can't use
# %%{gpgverify} the way fish.spec does. There's no rpm macro for minisign
# either -- verified as a plain shell command in %%prep instead, with the
# public key (from PACKAGING.md, checked out at the v%%{version} tag -- that
# file explicitly warns it is only accurate for the version alongside it)
# given directly on the command line. No keyring file is needed.
#
# RWQlAjJC23149WL2sEpT/l0QKy7hMIFhYdQOFy0Z7z7PbneUgvlsnYcV

# Ghostty requires Zig 0.15.2 (see build.zig.zon's minimum_zig_version).
# Fedora 44 ships Zig 0.16.0, and main only gained 0.16 compatibility after
# the v1.3.1 tag -- real breaking changes exist between the two, so building
# against the system Zig is not safe. A pinned, official Zig release tarball
# is vendored here as a build-time-only tool instead: it is extracted, put on
# PATH for the duration of %%install, and never installed as a system package
# or linked into anything.
Source2:        https://ziglang.org/download/0.15.2/zig-x86_64-linux-0.15.2.tar.xz

# The offline Zig dependency cache, pre-fetched by .woodpecker/ghostty.yaml's
# build step (which has internet access) via upstream's own
# nix/build-support/fetch-zig-cache.sh. rpmbuild itself needs no network
# access: %%install extracts this and points `zig build --system` at it,
# which upstream's PACKAGING.md documents as disabling all package fetching.
# Like fish.spec's Source3, this has a bare filename and no URL so that
# spectool skips it instead of failing to fetch it.
Source3:        %{name}-%{version}-zig-cache.tar.xz

BuildRequires:  gcc
BuildRequires:  gcc-c++
# Generates the .ui files from the .blp sources the release tarball ships.
BuildRequires:  blueprint-compiler
# Generates the HTML and man-page renderings of the markdown docs (-Demit-docs).
BuildRequires:  pandoc-cli
BuildRequires:  pkgconfig(gtk4)
BuildRequires:  pkgconfig(libadwaita-1)
BuildRequires:  pkgconfig(gtk4-layer-shell-0)
BuildRequires:  pkgconfig(oniguruma)
BuildRequires:  pkgconfig(harfbuzz)
BuildRequires:  pkgconfig(pixman-1)
BuildRequires:  pkgconfig(fontconfig)
BuildRequires:  pkgconfig(freetype2)
BuildRequires:  pkgconfig(glib-2.0)
BuildRequires:  pkgconfig(gio-2.0)
BuildRequires:  pkgconfig(gobject-2.0)
BuildRequires:  pkgconfig(x11)
BuildRequires:  pkgconfig(wayland-client)
BuildRequires:  pkgconfig(zlib)
BuildRequires:  pkgconfig(libpng16)
BuildRequires:  pkgconfig(bzip2)
# For minisign verification in %%prep.
BuildRequires:  minisign
# git+https://github.com/jacobsandlund/uucode is one of build.zig.zon.txt's
# entries, fetched into Source3 by the workflow -- not needed here. Nothing
# in %%prep/%%install touches git: --system disables all fetching, including
# that one.

%description
Ghostty is a terminal emulator that differentiates itself from other terminal
emulators by being fast, feature-rich, and native. It uses platform-native UI
and GPU acceleration, and is not developed as a side project by a single
maintainer but rather as a serious, dedicated application by a full-time
engineer.

%prep
minisign -Vm '%{SOURCE0}' -x '%{SOURCE1}' -P RWQlAjJC23149WL2sEpT/l0QKy7hMIFhYdQOFy0Z7z7PbneUgvlsnYcV
%autosetup -n %{name}-%{version}

%build
# Zig fuses "build" and "install" into a single step when --prefix/DESTDIR
# are given -- there is no separate compile-then-install split the way
# autotools/cmake have -- so setting up the toolchain and cache is all that
# happens here, and the actual `zig build` invocation lives in %%install
# where %%{buildroot} is available.
tar -xf '%{SOURCE2}' -C %{_builddir}
mkdir -p %{_builddir}/%{name}-zig-cache
tar -xf '%{SOURCE3}' -C %{_builddir}/%{name}-zig-cache

%install
export PATH=%{_builddir}/zig-x86_64-linux-0.15.2:$PATH
# --system triggers all of build.zig.zon's C-library dependencies to link
# dynamically against the system libraries pulled in via BuildRequires above.
# Libraries Fedora doesn't ship at all (highway, wuffs, spirv-cross, glslang,
# sentry, breakpad) and the pure-Zig dependencies (libxev, vaxis, z2d,
# zig_objc, zig_js, zf, uucode, the gobject wrapper, translate_c) are built
# from the vendored cache instead; nothing special is needed for those.
#
# zig build always installs libraries to $prefix/lib, not Fedora's lib64 --
# --prefix-lib-dir overrides that for libghostty-vt.so. The .pc file it
# generates is NOT affected by that flag (its destination is hardcoded
# upstream to share/pkgconfig/libghostty-vt.pc), so it stays under
# %%{_datadir} rather than %%{_libdir}/pkgconfig. That is not a mistake here:
# pkgconf's default search path includes /usr/share/pkgconfig, so it is still
# found.
#
# Flags mirror Arch's ghostty PKGBUILD (built against this same Zig 0.15.2),
# minus their 4-way subpackage split -- see %%files and the nautilus removal
# below for what that means here.
DESTDIR=%{buildroot} zig build \
    --prefix /usr \
    --prefix-lib-dir %{_libdir} \
    --system %{_builddir}/%{name}-zig-cache/p \
    -Doptimize=ReleaseFast \
    -Dcpu=baseline \
    -Dgtk-x11=true \
    -Dpie=true \
    -Demit-docs \
    -Dversion-string=%{version}-%{release} \
    --build-id=sha1 \
    --summary all

# Ghostty unconditionally installs a Nautilus (GNOME Files) right-click
# extension -- it's a plain Python file copy, not something that only builds
# when nautilus-python is present. Arch ships it as a separate
# ghostty-nautilus subpackage; this repo doesn't split packages without a
# concrete reason (see hyprwayland-scanner-devel in README.md for the one
# case that has one), so it's simply not installed here instead.
rm -rf %{buildroot}%{_datadir}/nautilus-python

%files
%license LICENSE
%doc README.md
%{_bindir}/ghostty
%{_libdir}/libghostty-vt.so
%{_libdir}/libghostty-vt.so.0*
%{_includedir}/ghostty/
%{_datadir}/pkgconfig/libghostty-vt.pc
%{_mandir}/man1/ghostty.1*
%{_mandir}/man5/ghostty.5*
%{_datadir}/applications/com.mitchellh.ghostty.desktop
%{_datadir}/metainfo/com.mitchellh.ghostty.metainfo.xml
%{_datadir}/icons/hicolor/*/apps/com.mitchellh.ghostty.png
%{_datadir}/dbus-1/services/com.mitchellh.ghostty.service
%{_userunitdir}/app-com.mitchellh.ghostty.service
%{_datadir}/kio/servicemenus/com.mitchellh.ghostty.desktop
# Docs, shell integration and the bundled theme collection (~300 files).
%{_datadir}/ghostty/
%{_datadir}/bash-completion/completions/ghostty.bash
%{_datadir}/fish/vendor_completions.d/ghostty.fish
%{_datadir}/zsh/site-functions/_ghostty
%{_datadir}/vim/vimfiles/compiler/ghostty.vim
%{_datadir}/vim/vimfiles/ftdetect/ghostty.vim
%{_datadir}/vim/vimfiles/ftplugin/ghostty.vim
%{_datadir}/vim/vimfiles/syntax/ghostty.vim
%{_datadir}/nvim/site/compiler/ghostty.vim
%{_datadir}/nvim/site/ftdetect/ghostty.vim
%{_datadir}/nvim/site/ftplugin/ghostty.vim
%{_datadir}/nvim/site/syntax/ghostty.vim
%{_datadir}/bat/syntaxes/ghostty.sublime-syntax
%{_datadir}/terminfo/g/ghostty
%{_datadir}/terminfo/x/xterm-ghostty
# 45 locale directories, listed as one glob rather than by hand.
%{_datadir}/locale/*/LC_MESSAGES/com.mitchellh.ghostty.mo

%changelog
* Sun Aug 30 2026 Saeverix - 1.3.1-1
- Initial package
