# Lua 5.5 is a hard requirement (see the %%build comment) and Fedora 44 only has
# 5.4.8, so a copy is built into the binary. Bumping this means bumping
# Provides: bundled(lua) below with it.
%global lua_ver 5.5.1

Name:           hyprland
Version:        0.56.1
Release:        1%{?dist}
Summary:        Dynamic tiling Wayland compositor with eye candy

# Hyprland is BSD-3-Clause. The statically linked Lua adds MIT.
License:        BSD-3-Clause AND MIT
URL:            https://github.com/hyprwm/Hyprland
# The release asset, not the autogenerated archive: this one carries the
# subprojects (udis86, tracy, hyprland-protocols) and, importantly, a
# src/version.h.in with the git metadata already substituted. That is why this
# package needs no git at build time and cannot pick up the surrounding
# repository's tag the way a git-describe build would.
#
# The asset is called source-v0.56.1.tar.gz upstream, hence the #/ rename.
Source0:        %{url}/releases/download/v%{version}/source-v%{version}.tar.gz#/%{name}-%{version}.tar.gz
Source1:        https://www.lua.org/ftp/lua-%{lua_ver}.tar.gz

Provides:       bundled(lua) = %{lua_ver}

BuildRequires:  gcc-c++
BuildRequires:  cmake >= 3.30
BuildRequires:  ninja-build
BuildRequires:  pkgconf-pkg-config
# Generates hl.meta.lua, the stub file for Lua config completion.
BuildRequires:  python3

# The hypr* stack, all built by this same workflow. Every version here is the one
# upstream's flake.lock pins for this Hyprland release; Fedora 44's own copies are
# too old across the board, which is why the whole set lives in this repo.
BuildRequires:  pkgconfig(aquamarine) >= 0.9.3
BuildRequires:  pkgconfig(hyprutils) >= 0.14.0
BuildRequires:  pkgconfig(hyprlang) >= 0.6.7
BuildRequires:  pkgconfig(hyprgraphics) >= 0.5.1
BuildRequires:  pkgconfig(hyprcursor) >= 0.1.7
BuildRequires:  pkgconfig(hyprwire)
BuildRequires:  pkgconfig(hyprland-protocols) >= 0.7.0
BuildRequires:  hyprwayland-scanner-devel >= 0.3.10
BuildRequires:  glaze-devel

BuildRequires:  glslang-devel
BuildRequires:  pkgconfig(wayland-server) >= 1.22.91
BuildRequires:  pkgconfig(wayland-protocols) >= 1.49
BuildRequires:  pkgconfig(wayland-scanner)
BuildRequires:  pkgconfig(xkbcommon) >= 1.11.0
BuildRequires:  pkgconfig(libinput) >= 1.29
BuildRequires:  pkgconfig(libdrm)
BuildRequires:  pkgconfig(gbm)
BuildRequires:  pkgconfig(glesv2)
BuildRequires:  pkgconfig(pixman-1)
BuildRequires:  pkgconfig(cairo)
BuildRequires:  pkgconfig(pango)
BuildRequires:  pkgconfig(pangocairo)
BuildRequires:  pkgconfig(gio-2.0)
BuildRequires:  pkgconfig(uuid)
BuildRequires:  pkgconfig(xcursor)
BuildRequires:  pkgconfig(libeis-1.0)
BuildRequires:  pkgconfig(re2)
BuildRequires:  pkgconfig(muparser)
BuildRequires:  pkgconfig(lcms2)
# hyprctl links readline for its interactive mode.
BuildRequires:  pkgconfig(readline)
# Disassembler used by the crash reporter. Fedora's udis86-devel ships no
# pkgconfig file, so Hyprland's pkg-config probe fails and it falls back to
# find_library, which finds /usr/lib64/libudis86.so -- the "udis86 dependency not
# found, falling back to subproject" line in the configure log means that fallback
# went further and used subprojects/udis86 instead. Either outcome builds.
BuildRequires:  udis86-devel

# XWayland is on unless NO_XWAYLAND is passed, and it is left on here.
BuildRequires:  pkgconfig(xcb)
BuildRequires:  pkgconfig(xcb-render)
BuildRequires:  pkgconfig(xcb-xfixes)
BuildRequires:  pkgconfig(xcb-icccm)
BuildRequires:  pkgconfig(xcb-composite)
BuildRequires:  pkgconfig(xcb-res)
BuildRequires:  pkgconfig(xcb-errors)

# Built with XWayland, so the X server has to be there at runtime.
Requires:       xorg-x11-server-Xwayland
# No runtime dependency on hyprland-protocols: the XML is turned into C++ at build
# time and compiled in, so nothing reads those files after the build.

%description
Hyprland is a dynamic tiling Wayland compositor with animations, rounded corners,
blur and per-window rules. It does not use wlroots: the backend, session and
device handling live in aquamarine, and configuration is either hyprlang or Lua.

Sessions are offered as "Hyprland" in any wayland-sessions aware display
manager, and a running instance is controlled with hyprctl.

%package        devel
Summary:        Development files for %{name}

%description    devel
Headers, generated protocol headers and the pkgconfig file needed to build
Hyprland plugins by hand.

%prep
# -a 1 unpacks the Lua tarball inside the source tree after Source0 is unpacked.
# %%autosetup cannot do that, so this is plain %%setup -- the same reason fish.spec
# uses it. -n is needed because the release asset unpacks to hyprland-source,
# not hyprland-%%{version}.
%setup -q -n hyprland-source -a 1

%build
# Hyprland's CMakeLists does
#   pkg_search_module(LUA REQUIRED ... lua55 lua5.5 lua-55 lua-5.5 lua>=5.5 lua<5.6)
# with no option to turn Lua off, and Fedora 44 ships 5.4.8 as the only Lua. So
# build 5.5 here, statically, into a private prefix and hand cmake a pkgconfig file
# for it. The search list is tried in order, so lua5.5.pc below is found before the
# system lua.pc is ever considered -- nothing on the system is touched or shadowed,
# and this whole block disappears the day the system Lua is 5.5 (Fedora rawhide
# already has it), leaving a plain BuildRequires behind.
#
# -fPIC because the result is linked into a PIE executable, and -fno-lto because
# Hyprland compiles itself with -fno-lto (upstream disables LTO so that plugins
# keep working) and a partly-LTO archive in that link is asking for trouble.
#
# -fvisibility=hidden is the important one, and it is not cosmetic. Fedora's
# libinput links liblua-5.4.so for its own plugin support, and Hyprland links
# libinput -- so both Lua versions end up in one process. Hyprland is built with
# -rdynamic (upstream sets CMAKE_EXECUTABLE_ENABLE_EXPORTS so plugins can resolve
# its symbols), and an executable is searched first when the loader resolves a
# DSO's undefined symbols. Without hidden visibility the binary exports 147 lua_*
# and luaL_* symbols, and libinput's calls -- compiled against 5.4 headers -- bind
# to this 5.5 implementation instead of to liblua-5.4.so. Nothing triggers it
# today, because Fedora ships no libinput plugin directory, but it is a real
# mismatch waiting for one to appear. Hidden visibility keeps these symbols local
# to the executable, so libinput resolves to its own Lua and Hyprland to this one.
# Verify with: nm -D --defined-only /usr/bin/Hyprland | grep -c ' lua_\| luaL_'
LUA_PREFIX=$PWD/lua-prefix
make -C lua-%{lua_ver}/src liblua.a \
    CC="%{__cc} -std=gnu99" \
    SYSCFLAGS="-DLUA_USE_LINUX" \
    MYCFLAGS="%{optflags} -fPIC -fno-lto -fvisibility=hidden"

install -Dm644 lua-%{lua_ver}/src/liblua.a $LUA_PREFIX/lib/liblua.a
install -Dm644 -t $LUA_PREFIX/include \
    lua-%{lua_ver}/src/lua.h \
    lua-%{lua_ver}/src/luaconf.h \
    lua-%{lua_ver}/src/lualib.h \
    lua-%{lua_ver}/src/lauxlib.h \
    lua-%{lua_ver}/src/lua.hpp

# Libs has to be -L/-l and NOT the absolute path to liblua.a. cmake's
# pkg_check_modules sorts an absolute library path into the target's link *options*
# rather than its link *libraries*, and link options are emitted before the object
# files -- so a static archive placed there gets scanned before anything references
# it and every symbol in it is discarded. That fails with "undefined reference to
# symbol 'lua_pushfstring'" while liblua.a is visibly on the link line. With -llua
# the imported target resolves it through find_library instead, and it lands after
# libhyprland_lib.a where a static archive belongs.
#
# -ldl is for package.loadlib, which LUA_USE_LINUX turns on.
mkdir -p $LUA_PREFIX/lib/pkgconfig
cat > $LUA_PREFIX/lib/pkgconfig/lua5.5.pc <<EOF
Name: lua5.5
Description: Lua language engine, bundled into Hyprland
Version: %{lua_ver}
Cflags: -I$LUA_PREFIX/include
Libs: -L$LUA_PREFIX/lib -llua -lm -ldl
EOF
export PKG_CONFIG_PATH=$LUA_PREFIX/lib/pkgconfig${PKG_CONFIG_PATH:+:$PKG_CONFIG_PATH}

# CMAKE_BUILD_TYPE is deliberately left unset. Hyprland reads it: Debug turns on
# its GTest suite (BUILD_TESTING) and drops -O3, anything else is treated as a
# release. Unset gives the release path while %%optflags still apply, which is what
# Fedora wants.
#
# NO_HYPRPM: hyprpm compiles plugins on the fly at runtime and would need cmake,
# meson and a compiler present on every installed system. Plugins can still be
# built by hand against %%{name}-devel.
%cmake -GNinja \
    -DNO_HYPRPM=ON
%cmake_build

%install
%cmake_install

%files
%license LICENSE
%doc README.md
%{_bindir}/Hyprland
# Lowercase alias upstream installs as a symlink to the above.
%{_bindir}/hyprland
%{_bindir}/hyprctl
%{_bindir}/start-hyprland
# Wallpapers and the "lock dead" screens, loaded at runtime -- not documentation.
%{_datadir}/hypr/
%{_datadir}/wayland-sessions/hyprland.desktop
# The uwsm session entry, installed because systemd and UWSM support are left at
# their upstream defaults. Fedora 44 has no uwsm package yet, so this second entry
# will not start until one exists (packaging uwsm here, or -DNO_UWSM=ON, both fix
# it). The plain hyprland.desktop above is unaffected.
%{_datadir}/wayland-sessions/hyprland-uwsm.desktop
# Screen sharing also needs xdg-desktop-portal-hyprland, which Fedora 44 does not
# have; this file is the compositor's half of that pairing and is harmless alone.
%{_datadir}/xdg-desktop-portal/hyprland-portals.conf
%{_datadir}/bash-completion/completions/hyprctl
%{_datadir}/fish/vendor_completions.d/hyprctl.fish
%{_datadir}/zsh/site-functions/_hyprctl
%{_mandir}/man1/Hyprland.1*
%{_mandir}/man1/hyprctl.1*

%files devel
%{_includedir}/hyprland/
# DATAROOTDIR, not libdir: upstream installs its pkgconfig file under
# %%{_datadir}. These are installed whether or not hyprpm is built, so they need a
# home either way.
%{_datadir}/pkgconfig/hyprland.pc

%changelog
* Wed Aug 05 2026 Saeverix - 0.56.1-1
- Initial package
