Name:           noctalia-greeter
Version:        1.3.1
Release:        1%{?dist}
# Verbatim from upstream's PACKAGING.md.
Summary:        A minimal login greeter for greetd that matches the look and feel of Noctalia Shell

# noctalia-greeter itself is MIT. third_party/wuffs (vendored, statically
# linked image decoder) is Apache-2.0 OR MIT -- same reasoning noctalia.spec
# already documents for the same vendored file.
License:        MIT AND Apache-2.0
URL:            https://github.com/noctalia-dev/noctalia-greeter
# Upstream creates no GitHub Releases for this repo (checked: the releases API
# returns an empty list) -- only tags. So this is the mangowm/scenefx pattern
# (autogenerated tag archive), not the ghostty pattern (uploaded release asset).
Source0:        %{url}/archive/refs/tags/v%{version}/%{name}-%{version}.tar.gz

BuildRequires:  gcc-c++
BuildRequires:  meson
BuildRequires:  ninja-build

BuildRequires:  pkgconfig(wayland-client)
BuildRequires:  pkgconfig(wayland-protocols)
BuildRequires:  pkgconfig(wayland-server)
BuildRequires:  pkgconfig(wayland-egl)
BuildRequires:  pkgconfig(wayland-scanner)
# No Qt or GTK: the UI is Wayland plus OpenGL ES. Upstream's README lists
# libEGL-devel / mesa-libGLES-devel, which are not Fedora 44 package names --
# the pkg-config names resolve to libglvnd-devel instead, same as noctalia.spec.
BuildRequires:  pkgconfig(egl)
BuildRequires:  pkgconfig(glesv2)
BuildRequires:  pkgconfig(xkbcommon)
BuildRequires:  pkgconfig(freetype2)
BuildRequires:  pkgconfig(fontconfig)
BuildRequires:  pkgconfig(cairo)
BuildRequires:  pkgconfig(cairo-ft)
BuildRequires:  pkgconfig(pango)
BuildRequires:  pkgconfig(pangocairo)
BuildRequires:  pkgconfig(pangoft2)
BuildRequires:  pkgconfig(harfbuzz)
BuildRequires:  pkgconfig(librsvg-2.0)
BuildRequires:  pkgconfig(glib-2.0)
BuildRequires:  pkgconfig(gobject-2.0)
BuildRequires:  pkgconfig(gio-2.0)
BuildRequires:  pkgconfig(wlroots-0.20)
BuildRequires:  pkgconfig(libinput)
BuildRequires:  pkgconfig(tomlplusplus)
BuildRequires:  pkgconfig(nlohmann_json)
# PACKAGING.md calls this optional ("only if you ship the matching feature"),
# but meson.build asks for it with required: true -- it is not actually
# optional for this build.
BuildRequires:  pkgconfig(libwebp)
# No .pc file: meson.build reaches this through cc.has_header(). Fedora ships
# it under the stb/-prefixed path meson checks for.
BuildRequires:  stb_image_resize2-devel

# noctalia-greeter-session wraps the compositor in dbus-run-session.
Requires:       dbus-daemon
# greetd starts this as its default_session; it is useless without it.
Requires:       greetd

# Only needed for the optional Noctalia Shell appearance-sync path
# (pkexec noctalia-greeter-apply-appearance). Login and local greeter.toml
# config work fine without it.
Recommends:     polkit

%description
Noctalia Greeter is a minimal login greeter for greetd: it lets you pick a
user, enter your password, choose a Wayland session, and pick a color scheme,
with the same visual language as Noctalia Shell.

It bundles its own wlroots compositor (noctalia-greeter-compositor); greetd
starts it through the session wrapper, noctalia-greeter-session. Pairing it
with Noctalia Shell (package noctalia) is optional and syncs wallpaper and
palette from the shell's own settings.

%prep
%autosetup -n %{name}-%{version}

%build
# %%meson defaults to --buildtype=plain, which is exactly what PACKAGING.md
# recommends for packaging: upstream's own "release" buildtype bakes in
# -march=native/-mtune=native, which is not portable across machines.
#
# -Db_pie=true is required: noctalia-greeter-compositor mixes a C source
# (src/compositor/noctalia_compositor.c) with C++ ones, and without this,
# meson does not add -fPIE to the C compile, while Fedora's hardened linker
# specs still force a PIE link -- ld then refuses with "relocation
# R_X86_64_32 against `.rodata' can not be used when making a PIE object".
# The C++-only executables link fine either way; this option is harmless for
# them.
%meson -Db_pie=true
%meson_build

%install
%meson_install

# Meson installs this tmpfiles.d drop-in unconditionally, and it hardcodes
# chown to "greeter:greeter". Fedora's own greetd package creates a "greetd"
# system user instead (sysusers.d) and its default /etc/greetd/config.toml
# runs the session as "greetd", not "greeter". PACKAGING.md itself says a
# differing session user should skip this drop-in and rely on %%post doing the
# chown instead -- which is exactly what happens below.
rm -f %{buildroot}%{_tmpfilesdir}/%{name}.conf

%post
# PACKAGING.md's own resolution precedence for the greeter's session user
# checks this directory's ownership before it ever tries to parse greetd's
# config, so chowning it here to Fedora's real session user ("greetd", see the
# %%install comment above) is what every shipped tool -- setup script,
# appearance sync -- needs to agree on one account without reading
# /etc/greetd/config.toml at all. greetd (Requires, above) already created
# that user by the time this scriptlet runs.
install -d -m 0750 -o greetd -g greetd %{_sharedstatedir}/%{name}

%files
%license LICENSE
%doc README.md PACKAGING.md examples/greeter.toml docs/user
%{_bindir}/noctalia-greeter
%{_bindir}/noctalia-greeter-compositor
%{_bindir}/noctalia-greeter-session
%{_bindir}/noctalia-greeter-apply-appearance
%{_bindir}/noctalia-greeter-print-greetd-config
# Required at runtime, not documentation: fonts, icons and the shipped setup
# scripts all live under here. Copying only the binaries breaks the UI.
%{_datadir}/noctalia-greeter/
%{_datadir}/polkit-1/actions/org.noctalia.greeter.apply-appearance.policy

%changelog
* Thu Sep 03 2026 Saeverix - 1.3.1-1
- Initial package
